name: CreateDocs

on:
  push:
    branches-ignore:
      - 'master'
    paths:

      - 'candidate-standard/EDR-candidate-specification2.adoc'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@v1
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          modules-
    - name: NPM Install
      run: npm install
      env:
        CI: true
    - name: AsciiDoctor-PDF
      run: npm run generate-pdf
    - name: Commit files
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "Actions"
        git add candidate-standard/EDR-candidate-specification.*
        git commit -m 'AsciiDoctor-PDF build from Actions'
        git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }}
  


